#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the checkMagazine function below.
def checkMagazine(magazine, note):
    '''
    print(Counter(note))
    print(Counter(magazine))
    print(Counter(magazine)-Counter(note))
    print(Counter(note)-Counter(magazine))
    '''
    if(Counter(note) - Counter(magazine)) == {} :
        print("Yes")
    else:
        print("No")
     
    

if __name__ == '__main__':
    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    magazine = input().rstrip().split()

    note = input().rstrip().split()

    checkMagazine(magazine, note)
 
